### ISSUE TITLE
Don't require phase in config

### ISSUE THREAD

**Issue by piejanssens** [meesvandongen/semantic-release-yaml#3]
First of all massive thanks for this plugin! 🙇 

Since now and for the foreseeable future, the only phase that is supported is the 'prepare' phase I would remove the command parameter (from the readme) and remove the filter in [the implementation](https://github.com/meesvandongen/semantic-release-yaml/blob/34448e0c4e6bfb4a7236ad9efa19fe13b4eda057/src/index.ts#L8).

**Comment by meesvandongen** [comment]
Makes sense, I'll get around to it soon(tm)
